version: '3.1'

services:
    yap_db:
      image: mysql:5.7
      restart: always
      ports:
        - 3106:3306
      environment:
        MYSQL_ROOT_PASSWORD: yap_root_password
        MYSQL_DATABASE: yap_test
        MYSQL_USER: yap_user
        MYSQL_PASSWORD: yap_password
        MYSQL_ROOT_HOST: '%'
