name: e2e-test
description: "Run Playwright E2E tests"

runs:
  using: composite
  steps:
    - name: Install npm dependencies
      run: |
        cd src
        npm ci
      shell: bash

    - name: Install Playwright Browsers
      run: |
        cd src
        npx playwright install chromium --with-deps
      shell: bash

    - name: Build frontend
      run: |
        cd src
        npm run build
      shell: bash

    - name: Setup env file
      run: |
        cd src
        mv .env.pipeline .env
      shell: bash

    - name: Run Playwright tests
      run: |
        cd src
        npx playwright test
      shell: bash

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v6
      if: always()
      with:
        name: ${{ matrix.php }}-playwright-report
        path: src/playwright-report/
        retention-days: 30

    - name: Upload test screenshots
      uses: actions/upload-artifact@v6
      if: failure()
      with:
        name: ${{ matrix.php }}-playwright-screenshots
        path: src/test-results/
        retention-days: 30

    - name: Upload server log
      uses: actions/upload-artifact@v6
      if: failure()
      with:
        name: ${{ matrix.php }}-server-log
        path: src/server.log
        retention-days: 30

    - name: Publish E2E Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "src/tests/e2e-results.xml"
        check_name: "E2E Test Results"
