name: e2e-test
description: "Run Playwright E2E tests"

runs:
  using: composite
  steps:
    - name: Install npm dependencies
      run: |
        cd src
        npm ci
      shell: bash

    - name: Install Playwright Browsers
      run: |
        cd src
        npx playwright install chromium --with-deps
      shell: bash

    - name: Build frontend
      run: |
        cd src
        npm run build
      shell: bash

    - name: Setup database
      run: |
        cd src
        mv .env.pipeline .env
        ENVIRONMENT=test php artisan migrate --force
        ENVIRONMENT=test php artisan db:seed --class=TestEnvironmentSeeder --force
      shell: bash

    - name: Start server
      run: |
        cd src
        ENVIRONMENT=test php -S 127.0.0.1:8000 -t . server.php > server.log 2>&1 &
        # Wait for server to be ready
        for i in {1..30}; do
          if curl -s http://127.0.0.1:8000/yap/admin/login > /dev/null 2>&1; then
            echo "Server is ready"
            break
          fi
          echo "Waiting for server... ($i)"
          sleep 2
        done
      shell: bash

    - name: Run Playwright tests
      run: |
        cd src
        BASE_URL=http://127.0.0.1:8000/yap npx playwright test
      shell: bash

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.php }}-playwright-report
        path: src/playwright-report/
        retention-days: 30

    - name: Upload test screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ${{ matrix.php }}-playwright-screenshots
        path: src/test-results/
        retention-days: 30

    - name: Upload server log
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ${{ matrix.php }}-server-log
        path: src/server.log
        retention-days: 30

    - name: Publish E2E Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "src/tests/e2e-results.xml"
        check_name: "E2E Test Results"
