name: 'pull-request'

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
        id: code-checkout

      - name: Validate composer.json and composer.lock
        id: composer-validate
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        id: install-dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          args: --prefer-dist --no-progress

      - name: PHPCS checker
        id: php-codesniffer
        run: vendor/squizlabs/php_codesniffer/bin/phpcs

      - name: Test
        id: run-tests
        run: set -e || vendor/pestphp/pest/bin/pest --configuration phpunit.xml tests --verbose

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#yap'
        if: failure()
