name: 'pull-request'

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.1"
          - "8.2"
          - "8.3"

    services:
      db-tests:
        image: 'mysql/mysql-server:8.0'
        env:
          MYSQL_ROOT_PASSWORD: yap_root_password
          MYSQL_DATABASE: yap_test
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3106:3306

    steps:
      - uses: actions/checkout@v4
        id: code-checkout

      - name: hydrate test database
        id: hydrate-test-database
        run: |
          mysql -uroot -p"$MYSQL_ROOT_PASSWORD" --port=3106 --host=127.0.0.1 --database=yap_test < tests/yap_test.sql
        env:
          MYSQL_ROOT_PASSWORD: yap_root_password

      - name: Setup PHP
        uses: ./.github/actions/setup-php

      - name: Install Dependencies
        uses: ./.github/actions/install-deps

      - name: Lint
        uses: ./.github/actions/lint

      - name: Test
        uses: ./.github/actions/test
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
